// Generates small test models in ../samples (no downloads needed).
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "samples");
mkdirSync(out, { recursive: true });

const sub = (a, b) => [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
const add = (a, b) => [a[0] + b[0], a[1] + b[1], a[2] + b[2]];
const cross = (a, b) => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]];
const normalize = (a) => {
    const l = Math.hypot(...a) || 1;
    return a.map((v) => v / l);
};
const faceNormal = (a, b, c) => normalize(cross(sub(b, a), sub(c, a)));

// Torus knot, Z-up, lifted so it sits above z=0 like a typical 3D-print STL (millimetres).
function torusKnot(p = 2, q = 3, R = 20, r = 6, tubular = 256, radial = 24, lift = 18) {
    const pos = [];
    const idx = [];
    const curve = (t) => {
        const qt = (q / p) * t;
        const cs = Math.cos(qt);
        return [R * (2 + cs) * 0.5 * Math.cos(t), R * (2 + cs) * 0.5 * Math.sin(t), R * Math.sin(qt) * 0.5];
    };
    for (let i = 0; i <= tubular; i++) {
        const u = (i / tubular) * p * Math.PI * 2;
        const P1 = curve(u);
        const P2 = curve(u + 0.01);
        const T = sub(P2, P1);
        const B = normalize(cross(T, add(P2, P1)));
        const N = normalize(cross(B, T));
        for (let j = 0; j <= radial; j++) {
            const v = (j / radial) * Math.PI * 2;
            const cx = -r * Math.cos(v);
            const cy = r * Math.sin(v);
            pos.push([P1[0] + cx * N[0] + cy * B[0], P1[1] + cx * N[1] + cy * B[1], P1[2] + cx * N[2] + cy * B[2] + lift]);
        }
    }
    for (let j = 1; j <= tubular; j++) {
        for (let i = 1; i <= radial; i++) {
            const a = (radial + 1) * (j - 1) + (i - 1);
            const b = (radial + 1) * j + (i - 1);
            const c = (radial + 1) * j + i;
            const d = (radial + 1) * (j - 1) + i;
            idx.push([a, b, d], [b, c, d]);
        }
    }
    return { pos, idx };
}

function box(min, max) {
    const [x0, y0, z0] = min;
    const [x1, y1, z1] = max;
    const pos = [[x0, y0, z0], [x1, y0, z0], [x1, y1, z0], [x0, y1, z0], [x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1]];
    const idx = [[0, 2, 1], [0, 3, 2], [4, 5, 6], [4, 6, 7], [0, 1, 5], [0, 5, 4], [1, 2, 6], [1, 6, 5], [2, 3, 7], [2, 7, 6], [3, 0, 4], [3, 4, 7]];
    return { pos, idx };
}

function uvSphere(radius, seg = 48, rings = 24, center = [0, 0, 0]) {
    const pos = [];
    const idx = [];
    const col = [];
    for (let y = 0; y <= rings; y++) {
        for (let x = 0; x <= seg; x++) {
            const u = x / seg;
            const v = y / rings;
            const th = u * Math.PI * 2;
            const ph = v * Math.PI;
            pos.push([center[0] - radius * Math.cos(th) * Math.sin(ph), center[1] + radius * Math.cos(ph), center[2] + radius * Math.sin(th) * Math.sin(ph)]);
            col.push([Math.round(255 * u), Math.round(255 * (1 - v)), 180]);
        }
    }
    for (let y = 0; y < rings; y++) {
        for (let x = 0; x < seg; x++) {
            const a = y * (seg + 1) + x;
            const b = a + seg + 1;
            idx.push([a, a + 1, b], [b, a + 1, b + 1]);
        }
    }
    return { pos, idx, col };
}

function binaryStl({ pos, idx }) {
    const buf = Buffer.alloc(84 + idx.length * 50);
    buf.write("binary STL generated by make-samples", 0);
    buf.writeUInt32LE(idx.length, 80);
    let o = 84;
    for (const [a, b, c] of idx) {
        for (const f of [...faceNormal(pos[a], pos[b], pos[c]), ...pos[a], ...pos[b], ...pos[c]]) {
            buf.writeFloatLE(f, o);
            o += 4;
        }
        o += 2;
    }
    return buf;
}

function asciiStl({ pos, idx }, name) {
    let s = `solid ${name}\n`;
    for (const [a, b, c] of idx) {
        s += `  facet normal ${faceNormal(pos[a], pos[b], pos[c]).join(" ")}\n    outer loop\n`;
        for (const v of [pos[a], pos[b], pos[c]]) s += `      vertex ${v.join(" ")}\n`;
        s += "    endloop\n  endfacet\n";
    }
    return s + `endsolid ${name}\n`;
}

function obj({ pos, idx }) {
    return (
        "# generated by make-samples\n" +
        pos.map((p) => `v ${p.join(" ")}`).join("\n") +
        "\n" +
        idx.map((t) => `f ${t.map((i) => i + 1).join(" ")}`).join("\n") +
        "\n"
    );
}

function ply({ pos, idx, col }) {
    let s =
        "ply\nformat ascii 1.0\n" +
        `element vertex ${pos.length}\nproperty float x\nproperty float y\nproperty float z\n` +
        "property uchar red\nproperty uchar green\nproperty uchar blue\n" +
        `element face ${idx.length}\nproperty list uchar int vertex_indices\nend_header\n`;
    s += pos.map((p, i) => `${p.join(" ")} ${col[i].join(" ")}`).join("\n") + "\n";
    s += idx.map((t) => `3 ${t.join(" ")}`).join("\n") + "\n";
    return s;
}

// Minimal GLB: a red box and a gold metallic sphere (Y-up, metres).
function glb() {
    const parts = [
        { geo: box([-0.6, 0, -0.3], [0, 0.6, 0.3]), color: [0.8, 0.1, 0.1, 1], metallic: 0, roughness: 0.4 },
        { geo: uvSphere(0.3, 48, 24, [0.4, 0.3, 0]), color: [0.95, 0.75, 0.3, 1], metallic: 1, roughness: 0.25 },
    ];
    const chunks = [];
    const bufferViews = [];
    const accessors = [];
    const meshes = [];
    const materials = [];
    let byteOffset = 0;
    const pushView = (arr) => {
        const b = Buffer.from(arr.buffer);
        chunks.push(b);
        bufferViews.push({ buffer: 0, byteOffset, byteLength: b.length, target: 34962 });
        byteOffset += b.length;
        return bufferViews.length - 1;
    };
    parts.forEach((m, i) => {
        const p = [];
        const n = [];
        for (const [a, b, c] of m.geo.idx) {
            const fn = faceNormal(m.geo.pos[a], m.geo.pos[b], m.geo.pos[c]);
            for (const k of [a, b, c]) {
                p.push(...m.geo.pos[k]);
                n.push(...fn);
            }
        }
        const pa = new Float32Array(p);
        const min = [Infinity, Infinity, Infinity];
        const max = [-Infinity, -Infinity, -Infinity];
        for (let j = 0; j < pa.length; j += 3) {
            for (let k = 0; k < 3; k++) {
                min[k] = Math.min(min[k], pa[j + k]);
                max[k] = Math.max(max[k], pa[j + k]);
            }
        }
        accessors.push({ bufferView: pushView(pa), componentType: 5126, count: pa.length / 3, type: "VEC3", min, max });
        accessors.push({ bufferView: pushView(new Float32Array(n)), componentType: 5126, count: pa.length / 3, type: "VEC3" });
        materials.push({ pbrMetallicRoughness: { baseColorFactor: m.color, metallicFactor: m.metallic, roughnessFactor: m.roughness } });
        meshes.push({ primitives: [{ attributes: { POSITION: 2 * i, NORMAL: 2 * i + 1 }, material: i }] });
    });
    const bin = Buffer.concat(chunks);
    const json = {
        asset: { version: "2.0", generator: "make-samples" },
        scene: 0,
        scenes: [{ nodes: [0, 1] }],
        nodes: [{ mesh: 0 }, { mesh: 1 }],
        meshes,
        materials,
        accessors,
        bufferViews,
        buffers: [{ byteLength: bin.length }],
    };
    let jsonBuf = Buffer.from(JSON.stringify(json));
    jsonBuf = Buffer.concat([jsonBuf, Buffer.alloc((4 - (jsonBuf.length % 4)) % 4, 0x20)]);
    const header = Buffer.alloc(12);
    header.writeUInt32LE(0x46546c67, 0);
    header.writeUInt32LE(2, 4);
    header.writeUInt32LE(12 + 8 + jsonBuf.length + 8 + bin.length, 8);
    const jh = Buffer.alloc(8);
    jh.writeUInt32LE(jsonBuf.length, 0);
    jh.writeUInt32LE(0x4e4f534a, 4);
    const bh = Buffer.alloc(8);
    bh.writeUInt32LE(bin.length, 0);
    bh.writeUInt32LE(0x004e4942, 4);
    return Buffer.concat([header, jh, jsonBuf, bh, bin]);
}

writeFileSync(join(out, "torus-knot.stl"), binaryStl(torusKnot()));
writeFileSync(join(out, "bracket-ascii.stl"), asciiStl(box([0, 0, 0], [40, 20, 5]), "bracket"));
writeFileSync(join(out, "knot.obj"), obj(torusKnot(3, 7, 2, 0.4, 400, 16, 0)));
writeFileSync(join(out, "sphere-colors.ply"), ply(uvSphere(1)));
writeFileSync(join(out, "box-and-ball.glb"), glb());
console.log("samples written to", out);
